config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new'
  # get 'tasks/:id', to: 'tasks#find', as: 'task'

  # get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  # patch 'tasks/:id', to: 'tasks#update'

  # delete 'tasks/:id', to: 'tasks#destroy', as: 'delete_task'
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  # before: find in filename | hard-coded routes
  def show; end

  # Creates a new empty task instance that the form_for helper can use as input.
  # form_for helper checks for ID. Since it is empty here, task gets created.
  # This is done via the action="post". For post updates, action="patch".
  # The different HTTP action means that another route (update not create) is called.
  def new
    @task = Task.new
  end

  # Is linked to the POST route of the form. Takes params and creates new DB entry.

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit "Submit" %>
<% end  %>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>
<%= render "form", task: @task %>

<br><br>
<%= link_to "Back to all tasks", tasks_path %>

app/views/tasks/find.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>
<input type="checkbox" <%= "checked" if @task.completed == true %>>

<%= if @task.completed == true
    "This task is completed."
else
    "This task is not completed."
end  %>
<br><br>
<%= link_to "Edit this task", edit_task_path %>
<br><br>
<%= link_to "Back to all tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul style="list-style-type:none; padding: 0px;">
<% @tasks.each do |task| %>
  <li><input type="checkbox" <%= "checked" if task.completed == true %>>
   <%= link_to task.title, task_path(task) %> |
   <%= link_to "Delete task", task_path(task), method: :delete, data: {confirm: "Are you sure?"} %>
  </li>
<% end %>
</ul>

<br><br>
<%= link_to "Add a new task", new_task_path %> <!-- tasks_new_path bei hardcoded routes -->

app/views/tasks/new.html.erb
<h1>Add a new task</h1>
<%= render "form", task: @task %>

<br><br>
<%= link_to "Back to all tasks", tasks_path %>

app/views/tasks/show.html.erb
<!-- before: find in filename | hard-coded routes -->

<h1><%= @task.title %></h1>

<p><%= @task.details %></p>
<input type="checkbox" <%= "checked" if @task.completed == true %>>

<%= if @task.completed == true
    "This task is completed."
else
    "This task is not completed."
end  %>
<br><br>
<%= link_to "Edit this task", edit_task_path %>
<br><br>
<%= link_to "Back to all tasks", tasks_path %>